begin;
select plan(8);
select ok((select relrowsecurity from pg_class where oid = 'public.academic_calendars'::regclass), 'Calendar RLS is enabled');
select ok(not has_table_privilege('anon', 'public.academic_calendars', 'SELECT'), 'Anonymous cannot read drafts');
select ok(not has_table_privilege('authenticated', 'public.academic_calendars', 'SELECT'), 'Authenticated cannot read drafts');
select ok(not has_table_privilege('authenticated', 'public.academic_calendars', 'UPDATE'), 'Authenticated cannot edit calendar');
select ok(has_table_privilege('service_role', 'public.academic_calendars', 'SELECT'), 'Server can read calendar');
select ok(has_table_privilege('service_role', 'public.academic_calendars', 'UPDATE'), 'Server can update calendar');
select ok(not has_table_privilege('service_role', 'public.academic_calendars', 'DELETE'), 'Server cannot delete institution row');
select is((select count(*)::integer from public.academic_calendars where id = 'ufape'), 1, 'Institution singleton exists');
select * from finish();
rollback;
