"""Render the official calendar into responsive WebP pages (Pillow + Poppler)."""
import argparse
import json
from pathlib import Path
import shutil
import subprocess
import tempfile

from PIL import Image


ROOT = Path(__file__).resolve().parent.parent


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--pdf', type=Path, default=ROOT / 'public/documents/calendario-academico-ufape-2026.pdf')
    parser.add_argument('--poppler-dir', type=Path)
    args = parser.parse_args()
    poppler = str(args.poppler_dir / 'pdftoppm.exe') if args.poppler_dir else shutil.which('pdftoppm')
    if not poppler:
        parser.error('Install Poppler or pass --poppler-dir with its bin directory.')
    output = ROOT / 'public/documents/calendario-academico-ufape-2026'
    output.mkdir(parents=True, exist_ok=True)
    scratch = ROOT / 'tmp/pdfs'
    scratch.mkdir(parents=True, exist_ok=True)
    pages = []
    with tempfile.TemporaryDirectory(prefix='calendar-images-', dir=scratch) as temporary:
        prefix = Path(temporary) / 'page'
        subprocess.run([poppler, '-png', '-scale-to-x', '2400', '-scale-to-y', '-1', str(args.pdf.resolve()), str(prefix)], check=True)
        renders = sorted(Path(temporary).glob('page-*.png'), key=lambda p: int(p.stem.split('-')[-1]))
        if not renders:
            raise RuntimeError('No pages were rendered.')
        for number, rendered in enumerate(renders, start=1):
            with Image.open(rendered) as original:
                image = original.convert('RGB')
                sources = []
                for width in (800, 1600, 2400):
                    height = round(image.height * width / image.width)
                    name = f'page-{number:02d}-{width}.webp'
                    resized = image.resize((width, height), Image.Resampling.LANCZOS)
                    resized.save(output / name, 'WEBP', quality=90, method=6)
                    sources.append({'width': width, 'path': f'/documents/{output.name}/{name}'})
                pages.append({'page': number, 'width': image.width, 'height': image.height, 'sources': sources})
                print(f'Rendered page {number}/{len(renders)}', flush=True)
    manifest = ROOT / 'src/data/academicCalendarImages.ts'
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text('// Generated by scripts/renderAcademicCalendar.py; regenerate when the PDF changes.\n'
                        + 'export const academicCalendarImages = '
                        + json.dumps(pages, ensure_ascii=False, indent=2) + ' as const;\n', encoding='utf-8')
    total = sum((output / Path(source['path']).name).stat().st_size for page in pages for source in page['sources'])
    print(f'{len(pages)} pages, {total / 1024 / 1024:.2f} MiB of WebP assets.', flush=True)


if __name__ == '__main__':
    main()
