// Generated by scripts/renderAcademicCalendar.py; regenerate when the PDF changes.
export const academicCalendarImages = [
  {
    "page": 1,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-01-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-01-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-01-2400.webp"
      }
    ]
  },
  {
    "page": 2,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-02-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-02-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-02-2400.webp"
      }
    ]
  },
  {
    "page": 3,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-03-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-03-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-03-2400.webp"
      }
    ]
  },
  {
    "page": 4,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-04-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-04-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-04-2400.webp"
      }
    ]
  },
  {
    "page": 5,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-05-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-05-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-05-2400.webp"
      }
    ]
  },
  {
    "page": 6,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-06-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-06-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-06-2400.webp"
      }
    ]
  },
  {
    "page": 7,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-07-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-07-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-07-2400.webp"
      }
    ]
  },
  {
    "page": 8,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-08-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-08-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-08-2400.webp"
      }
    ]
  },
  {
    "page": 9,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-09-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-09-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-09-2400.webp"
      }
    ]
  },
  {
    "page": 10,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-10-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-10-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-10-2400.webp"
      }
    ]
  },
  {
    "page": 11,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-11-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-11-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-11-2400.webp"
      }
    ]
  },
  {
    "page": 12,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-12-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-12-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-12-2400.webp"
      }
    ]
  },
  {
    "page": 13,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-13-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-13-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-13-2400.webp"
      }
    ]
  },
  {
    "page": 14,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-14-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-14-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-14-2400.webp"
      }
    ]
  },
  {
    "page": 15,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-15-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-15-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-15-2400.webp"
      }
    ]
  },
  {
    "page": 16,
    "width": 2400,
    "height": 3395,
    "sources": [
      {
        "width": 800,
        "path": "/documents/calendario-academico-ufape-2026/page-16-800.webp"
      },
      {
        "width": 1600,
        "path": "/documents/calendario-academico-ufape-2026/page-16-1600.webp"
      },
      {
        "width": 2400,
        "path": "/documents/calendario-academico-ufape-2026/page-16-2400.webp"
      }
    ]
  }
] as const;
